# kubectl create clusterrole cluster-viewer --verb=get,list,watch --resource='*' --dry-run=client -o yaml | tee learning/rbac/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch

---
# kubectl create clusterrolebinding cluster-viewer-binding --clusterrole=cluster-viewer --group=viewer --dry-run=client -o yaml | tee cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: cluster-viewer
