apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.exposedPorts }}
    - name: {{ .name }}
      targetPort: {{ .name }}
      port: {{ .externalPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
